# Generated by Django 3.1.4 on 2020-12-22 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0003_auto_20201206_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='patient', max_length=10)),
                ('BloodType', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=250)),
                ('user_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='doctor.doctor')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='patient.patient')),
            ],
            options={
                'unique_together': {('patientId', 'doctorId')},
            },
        ),
    ]
