# Generated by Django 3.1.4 on 2020-12-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20201205_1903'),
        ('patient', '0002_auto_20201222_1725'),
    ]

    operations = [
    ]
