# Generated by Django 3.1.4 on 2020-12-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20201222_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='userId',
            new_name='user_Id',
        ),
    ]
