# Generated by Django 3.1.4 on 2020-12-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '__first__'),
        ('day', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='hour',
            unique_together={('patientId', 'dayId')},
        ),
    ]
