# Generated by Django 3.1.4 on 2020-12-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '__first__'),
        ('day', '0002_auto_20201209_1912'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hour',
            unique_together={('patientId', 'dayId'), ('hour', 'dayId')},
        ),
    ]
