# Generated by Django 3.1.4 on 2020-12-11 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '__first__'),
        ('day', '0003_auto_20201211_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='doctorId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Appointemnt', to='doctor.doctor'),
        ),
    ]
