# Generated by Django 3.1.4 on 2020-12-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '__first__'),
        ('day', '0005_auto_20201211_2214'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('date', 'doctorId')},
        ),
    ]
