# Generated by Django 3.1.4 on 2020-12-12 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '__first__'),
        ('day', '0006_auto_20201211_2230'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hour',
            unique_together={('patientId', 'dayId'), ('patientId', 'hour'), ('hour', 'dayId')},
        ),
    ]
